### PR TITLE
release: 0.4.0 + many small fixes

### LINKED ISSUE #85: video marc21 translations: 8XX
- [x] `852__2`: 1047445, mistake, move to `852__z`:physical_medium.note
- [x] `852__8`: sequence_number (link to 340)
- [x] `852__9`: internal_note
- [x] `852__a`: location
- [x] `852__b`: sub_location
- [x] `852__c`: shelf
- [x] `852__d`: ignore
- [x] ~~`852__g`~~ mistake on 1109586
- [x] `852__j`: ignore
- [x] `852__t`: copy_number
- [x] `852__x`: ignore
- [x] `859__f`: _access.update

Files
--
- [x] `8564_8`
- [x] `8564_d`
- [x] `8564_q`
- [x] `8564_s`
- [x] `8564_u`
- [x] `8564_x`
- [x] `8564_y`
- [x] `8564_z`: verify if they are only used for BibDocFiles
- [x] `8567_2`
- [x] `8567_d`
- [x] `8567_u`
- [x] `8567_x`
- [x] `8567_y`

### PR DESCRIPTION
**Pull request by hachreak**
* Adds 8564_*, 852__x inside ignore list. (closes #85)

Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

### CODE REVIEW

**Comment by hachreak** [comment]
ping @drjova

**Comment by hachreak** [comment]
still working in progress... :smile:

**Comment by switowski** [comment]
I thought the `retry` commit was to make travis pass and you forgot to remove the `WIP` from the title :P Anyway, looks good so far :smile:

**Comment by hachreak** [comment]
ping @egabancho @drjova

**Pull request merged**
