### PR TITLE
New iteration of rules and updated ignored fields

### LINKED ISSUE #162: Migrator - to fix in cleaning tool
- [ ] decide about CDS legacy internal fields - migration or ignore (bottom of the [migration rules table](https://docs.google.com/spreadsheets/d/1DkHfR95aM0pm-DaUyB1J0QOdLQ0FYDBM-k1MXumbjI4/edit))

- [ ] fix problem with ‘fre’ value, not with ‘eng’ in the language field `041_a`

- [ ] implement fields `080` and `082` rules - > subject classification, depending on the key, its different value of the schema field

- [ ] implement `490`, `520` field rule

- [ ] ignore fields for `340`, `852`, `916` - they are connected with `Item` model (old name Holding), not book model

- [ ] ignore `963` field (it is in ignored keys of the model, check if it works properly)

### PR DESCRIPTION
**Pull request by kprzerwa**
(closes #162)

### CODE REVIEW

**Comment by kprzerwa** [comment]
To be merged after #161

**Comment by ntarocco** [comment]
@kprzerwa rebase needed!

**Comment by kprzerwa** [comment]
@ntarocco, @topless rebased, ready to be reviewed

**Comment by kprzerwa** [comment]
small refactor done, ready to merge

**Pull request merged**
