### PR TITLE
deposit schemas recompiled and split into base + the rest

### PR DESCRIPTION
**Pull request by switowski**

### CODE REVIEW

**Comment by switowski** [comment]
In the compiled schemas, this `$ref`: https://github.com/switowski/cds-dojson/blob/17812131153a00556eaa93b36ebdd5af1d15f409/cds_dojson/schemas/deposits/records/videos/video/video-v1.0.0.json#L172 has a wrong path, but it's being added by `invenio-deposit` and I have no idea how to remove it in an elegant way :/ (also there is no harm in keeping it I guess?)

**Comment by switowski** [comment]
Ok, so I replaced the `_resolve_references_sub` function with the `jsonref` package that has $ref resolving out of the box, as advised by @nharraud. Unfortunately, it won't resolve the `invenio-deposit` relative reference to `invenio-files` (it's too much magic even for this package :D ),  so we have to import all schemas into this repo and keep them in sync.

**Comment by nharraud** [comment]
@switowski is the $ref a standard URL ref as described [here](https://spacetelescope.github.io/understanding-json-schema/structuring.html#reuse)


*ref can also be a relative or absolute URI, so if you prefer to include your definitions in separate files, you can also do that. For example:*
```
{ "$ref": "definitions.json#/address" }
```

**Comment by switowski** [comment]
@nharraud the problem was with this guy: https://github.com/inveniosoftware/invenio-deposit/blob/master/invenio_deposit/jsonschemas/deposits/deposit-v1.0.0.json#L83 . Even when I used the  URL to the invenio-deposit schema on github, jsonref was complaining about this `$ref`. Anyway, it works now.

**Comment by nharraud** [comment]
Strange. You might want to ask @krzysztof as I think Zenodo also resolves references and uses invenio-deposit.

**Comment by switowski** [comment]
ping @egabancho

**Comment by switowski** [comment]
zenodo uses it as we used at the beginning, so with a URL to zenodo.org website: https://github.com/zenodo/zenodo/blob/fb2fb960e2719b062655125d9bcb06d3ac2a70a6/zenodo/modules/deposit/jsonschemas/deposits/records/record_src-v1.0.0.json#L8
But for us, since the cdslabs-qa has a _slightly_ invalid SSL certificate for the time being, we had to change it and that started the whole hassle.

**Comment by switowski** [comment]
@egabancho ok, I have rebased and the tests should be passing.
So far I thought that writing json schemas is hard, but rebasing JSON schemas is even a bigger nightmare :D Hopefully they will work.

**Comment by switowski** [comment]
:fireworks:

**Pull request merged**
